### ISSUE TITLE
Add ability to use ffbase without loading it on the search path

### ISSUE THREAD

**Issue by schuemie** [edwindj/ffbase#41] opened 2015-05-04 06:12 UTC
We like ff and ffbase, and are using it in our packages. However, ff and ffbase have quite a big impact on the R search path, so we would like to Import them rather than say 'Depends' in the description file. (There's also the huge amount of warnings that are thrown when loading the packages that are a bit ugly)

Most things work by using explicit package references, for example `ff::as.ram.ff()`, but some others don't. Would it be possible to fix those? 

Here's the list I have so far:
  - ffbase::save.ffdf() has a dependency on bit that is not explicit. This [line](https://github.com/edwindj/ffbase/blob/4941fc1fbb4bbb37d7aef9e002ca33d329169360/pkg/R/save_ffdf.R#L71) should refer to bit::physical()

  - ffbase::merge.ffdf() is not exported

  - ffbase::as.ram.ffdf() is not exported

**Comment by edwindj** [comment] 2015-05-04 06:42
Thanks for the suggestions! I will look into it and submit a new version to CRAN.

Thanks!

**Comment by edwindj** [comment] 2015-05-23 12:21
It should be fixed with the current version in github.
Using `devtools::install_github('edwindj/ffbase')` could you check if it works for you?

Closing it for now, but willing to reopen if needed.

**Comment by schuemie** [comment] 2015-05-24 09:23
Thanks! Almost there, but I would need `subset.ffdf()` to be exported as well.

**Comment by edwindj** [comment] 2015-05-25 09:25
Thanks! . Not exporting the functions is due to a roxygen change. The old version of roxygen used to export the function as well as implement it as a method. For the new roxygen version I need to do both.  I missed `subset.ffdf` (sorry about that). 
Should be fixed shortly.

**Comment by edwindj** [comment] 2015-05-27 07:56
On CRAN now...

**Comment by schuemie** [comment] 2015-06-01 06:28
There are now two functions I'm using that used to be ok, but are no longer available:
```r
ffbase::sum.ff()
ffbase::unique.ff()
```
Also, would it be possible to add
```r
ffbase::any.ff
```

**Comment by edwindj** [comment] 2015-06-01 06:30
Could you check with the latest github version if this is still failing?
Op 1 jun. 2015 08:28 schreef "Martijn Schuemie" <notifications@github.com>:

**Comment by schuemie** [comment] 2015-06-01 06:35
Sorry, same problems with the latest version on GitHub.

**Comment by edwindj** [comment] 2015-06-01 07:08
Strange...
In the NAMESPACE file in github (https://github.com/edwindj/ffbase/blob/master/pkg/NAMESPACE) explicitly `sum.ff` and `unique.ff` are exported.

You did install with:

```install_github("edwindj/ffbase", subdir="pkg")``` ?

What is the packageversion? `packageVersion("ffbase")`, should be "0.12.1.9000"

**Comment by schuemie** [comment] 2015-06-01 07:43
I could have sworn it wasn't working, but after reinstalling from GitHub it now works like a charm!

Thanks!

**Comment by edwindj** [comment] 2015-06-01 07:46
And thank you for reporting! I will sent a new version CRAN this evening.

**Comment by schuemie** [comment] 2015-06-04 07:01
Please don't forget to push the current GitHub version to CRAN ;-)

What is now on CRAN is wreaking havoc on our continuous integration server (because of the sum.ff thing).

**Comment by edwindj** [comment] 2015-06-04 10:55
Thanks for the reminder! 
I am checking for other problems before sending it to CRAN (because high frequency updates on packages are not allowed, except for real bugs). I will upload it tomorrow morning and let you know. 

Sorry for the inconvenience...

**Comment by msuchard** [comment] 2015-06-05 03:48
Before the CRAN submit,  might you also have a moment to patch two missing `bit` namespace qualifiers (similar to those pointed out by Martijn above) `ffappend.R` lines 80, 86?

``
physical(...) -> bit::physical(...)
``

Without the qualifiers, we seem to be forced to `depend` on `bit` instead of `import`.  Many, many thanks!

**Comment by edwindj** [comment] 2015-06-05 05:45
@msuchard. Thanks for the suggestion, it solves also issue #43.

Could you check if the lates github version is working for you?

```
devtools::install_github('edwindj/ffbase', subdir="pkg"))
```
Thanks!

**Comment by schuemie** [comment] 2015-06-05 08:03
This latest version works for me (Marc: both CohortMethod and Cyclops pass check). Marc, do you need to do some extra testing?

**Comment by msuchard** [comment] 2015-06-05 13:20
Thank you, @edwindj !   I can confirm that HEAD now fixes the following error:

```{r}
 Error in lapply(X = X, FUN = FUN, ...) : 
  could not find function "physical" 
5 lapply(X = X, FUN = FUN, ...) 
4 sapply(physical(x)[names(fc)], is.factor.ff) 
3 ffbase::ffdfappend(data, batch) at HelperFunctions.R#108
2 DatabaseConnector::dbGetQuery.ffdf(conn, translatedSql, batchSize = 10) 
```

`bit::physical()` is now found.  When you get a chance, please upload to CRAN.  That will keep my friend @schuemie from hating me for a while longer :-)

**Comment by edwindj** [comment] 2015-06-05 13:55
On it's way to CRAN...

**Closed** 2015-06-06 11:55 UTC
